# Generated by Django 5.0.6 on 2024-12-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['name', 'price'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='characteristics',
            field=models.JSONField(blank=True, null=True, verbose_name='Характеристики товара'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='quantity',
            field=models.PositiveSmallIntegerField(verbose_name='Количество товара'),
        ),
    ]
