# Generated by Django 5.1 on 2024-08-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='characteristics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
