services:
  django:
    build:
      context: .
    ports:
      - 8000:8000
    restart: always
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
    volumes:
      - ./src:/src
    command: >
      sh -c "
        python manage.py migrate --no-input &&
        python manage.py runserver 0.0.0.0:8000 --settings=config.settings.local"
    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
