services:
  django:
    build:
      context: .
    ports:
      - 8000:8000
    restart: always
    env_file: .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
    volumes:
      - ./src:/src
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=glance
      - POSTGRES_USER=glance-user
      - POSTGRES_PASSWORD=glance
