# Generated by Django 5.0.6 on 2024-12-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='goods',
        ),
        migrations.AddField(
            model_name='cart',
            name='goods',
            field=models.ManyToManyField(to='goods.goods'),
        ),
    ]
